### ISSUE TITLE
LoggerUI source code

### ISSUE THREAD

**Issue by olluz** [MetanoKid/msbuild-flame-graph#10]
Hi Carlos,
sorry for writing here, but I didn't find any other means to conact you.
I've followed your LoggerUI tutorial, thank you a lot for this. 
[https://metanokid.github.io/coding-scars/log-window-0](url)
I can't get the UI to look and function the way you did in the tutorial. I guess I must have missed something.
Do you by any chance have the source code available ?

Thanks in advance!

**Comment by MetanoKid** [comment]
Hi @olluz!

Indeed, I have the source but never got the chance to share it publicly. I guess this is a good time to do so!
I'll get it together, create a new repo and come back to you when it's done.

Thank you for the interest!

**Comment by MetanoKid** [comment]
Hi again 👋 

Here it is: https://github.com/MetanoKid/logger-wpf
Hope it's useful!

**Comment by olluz** [comment]
Thank you very much for releasing the sources. It works like a charm. Muchas gracias!
