### ISSUE TITLE
Doesn't compile. " You must add a reference to assembly 'netstandard...'"

### ISSUE THREAD

**Issue by leetNightshade** [MetanoKid/msbuild-flame-graph#5]
```
1>C:\Dev\msbuild-flame-graph-master\src\MSBuildWrapper\SolutionCompiler\DataExtractor\CustomEventFormatExtractor.cs(49,41,49,59): error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
1>C:\Dev\msbuild-flame-graph-master\src\MSBuildWrapper\Compilation\Compilation.cs(94,27,94,48): error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

Adding the following line to MSBuildWrapper.csproj seems to fix the issue, for me:

`<Reference Include="netstandard" />`

**Comment by MetanoKid** [comment]
Hello @leetNightshade, thank for opening the issue.

Were you building the solution within Visual Studio? If so, can you share which version it was?

On my end, I was able to build `MSBuildWrapper.csproj` without adding `<Reference Include="netstandard" />` and still builds when adding it. However, I'm hesitant to add it without knowing why it's needed.

My best guess comes from dotnet/standard#534. `MSBuildWrapper.csproj` references NuGet packages for `Microsoft.Build` and those depend on `System.Collections.Immutable 1.5.0`.

Still, it would be nice being able to reproduce it before adding the proposed fix.

**Comment by MetanoKid** [comment]
Just tested this environment in a Virtual Machine:

  * Clean Windows 10 Home installation.
  * Visual Studio 2017 with .NET Desktop Development workload + .NET Framework 4.6.2 SDK and Targeting Pack.

It compiled and ran without errors.
Need reproductibility.

**Comment by leetNightshade** [comment]
Info on the setup I'm using in this case:

Microsoft Visual Studio Community 2017 
Version 15.9.17
VisualStudio.15.Release/15.9.17+28307.905
Microsoft .NET Framework
Version 4.8.03752

Visual C++ 2017   00369-60000-00001-AA052
Microsoft Visual C++ 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Comment by leetNightshade** [comment]
If you google, "You must add a reference to assembly netstandard", you'll see your project is one of many who ran into this problem. I don't have details why this is the case.

**Comment by MetanoKid** [comment]
Thanks for your time, @leetNightshade!
